version: '3.3'

services:

  web:
    build:
      context: ./web
    restart: always
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - ./web/conf.d:/etc/nginx/conf.d
      - ./web/app-angular/:/usr/share/nginx/html/
    networks:
      - nginx_network

  app:
    build:
      context: ./app
    restart: always
    depends_on:
      - mariadb
    networks:
      - nginx_network

  mariadb:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
      - MARIADB_USER=riga
      - MARIADB_PASSWORD=pwd 
      - MARIADB_ROOT_PASSWORD=root-pwd 
    volumes:
      - mariadb-data:/var/lib/mysql
      - ./db/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    networks:
      - nginx_network

  phpMyAdmin:
    image: phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mariadb
    depends_on:
      - mariadb
    networks:
      - nginx_network

volumes:
  mariadb-data:

networks:
  nginx_network:
    driver: bridge




  
