services:
  mariadb:
    image: mariadb
    restart: always
    ports:
      - 306:3306
    environment:
      - MARIADB_USER=riga
      - MARIADB_PASSWORD=pwd 
      - MARIADB_ROOT_PASSWORD=root-pwd 
    volumes:
      - mariadb-data:/var/lib/mysql
  
  phpMyAdmin:
    image: phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mariadb
    depends_on:
      - mariadb

volumes:
  mariadb-data:
